export const SOCKET_CREATE_ROOM = 'SOCKET_CREATE_ROOM'
export const SOCKET_JOIN_ROOM = 'SOCKET_JOIN_ROOM'
export const SOCKET_UPDATE_AVAILABLE_ROOMS = 'SOCKET_UPDATE_AVAILABLE_ROOMS'
export const SOCKET_UPDATE_ROOM = 'SOCKET_UPDATE_ROOM'
